spring.application.name=bff-libros
azure.functions.usuarios-url=https://biblioteca-usuarios-bhenhgcdejdbdubu.eastus2-01.azurewebsites.net/api
azure.functions.prestamos-url=https://biblioteca-prestamos-h9eugbg9a8cbgcfk.eastus2-01.azurewebsites.net/api
azure.functions.libros-url=https://biblioteca-libros-dvf7f4bhgagjgvdd.eastus2-01.azurewebsites.net/api
azure.functions.reportes-url=https://biblioteca-reportes-edduhwh0bdbpejgu.eastus2-01.azurewebsites.net/api